"""2

Revision ID: e4224d22b641
Revises: dfaa08d94b4e
Create Date: 2026-02-26 15:46:15.367024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4224d22b641'
down_revision: Union[str, Sequence[str], None] = 'dfaa08d94b4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'passport_serial',
               existing_type=sa.VARCHAR(length=4),
               nullable=True)
    op.alter_column('documents', 'passport_number',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)
    op.alter_column('documents', 'snils',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
    op.alter_column('documents', 'insurance',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'insurance',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.alter_column('documents', 'snils',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
    op.alter_column('documents', 'passport_number',
               existing_type=sa.VARCHAR(length=6),
               nullable=False)
    op.alter_column('documents', 'passport_serial',
               existing_type=sa.VARCHAR(length=4),
               nullable=False)
    # ### end Alembic commands ###
